#pragma once
#include <map>
#include <utility>
#include <string>
#include <vector>

class ConstantTable;
class ConstantTableItem;
class MethodTableElement;
class MethodTable;
class TypeNode;
class FuncDeclNode;
class ClassDeclNode;
class ConstructorDeclNode;
class StmtListNode;
class ExternalMethodTable;

enum MethodAccessFlag {
    M_ACC_PUBLIC = 0x0001,        //	Declared public; may be accessed from outside its package.
    M_ACC_PRIVATE = 0x0002,       //	Declared private; accessible only within the defining class.
    M_ACC_PROTECTED = 0x0004,     //	Declared protected; may be accessed within subclasses.
    M_ACC_STATIC = 0x0008,        //	Declared static.
    M_ACC_FINAL = 0x0010,         //	Declared final; must not be overridden(§5.4.5).
    M_ACC_SYNCHRONIZED = 0x0020,  //	Declared synchronized; invocation is wrapped by a monitor use.
    M_ACC_BRIDGE = 0x0040,        //	A bridge method, generated by the compiler.
    M_ACC_VARARGS = 0x0080,       //	Declared with variable number of arguments.
    M_ACC_NATIVE = 0x0100,        //	Declared native; implemented in a language other than Java.
    M_ACC_ABSTRACT = 0x0400,      //	Declared abstract; no implementation is provided.
    M_ACC_STRICT = 0x0800,        //	Declared strictfp; floating - point mode is FP - strict.
    M_ACC_SYNTHETIC = 0x1000,     //	Declared synthetic; not present in the source code.
};

/*! \brief Структура, описывающая таблицу классов. */
class ClassTable
{
public:
    /// Укащатель на контейнер элементов таблицы.
    std::map<std::string, class ClassTableElement*> items;

    ClassTableElement* addClass(std::string name, std::string superName);

};

class ClassTableElement {
public:
    ClassTableElement(std::string name, std::string superName);

    void addRtlExternalMethods();

    // Ссылка на константу с именем класса - номер константы.
    // UTF-8?
    int name;

    /// Флаг, показывающий открыт ли класс для наследования.
    int isOpen = 0;

    // Ссылка на константу с именем родительского класса - номер константы.
    int superName = NULL;

    // Ссылка на константу текущего класса.
    // Class??
    int thisClass;

    // Ссылка на константу родительского класса.
    // Class??
    int superClass;

    std::string nameStr;

    ConstantTable* constants;

    MethodTable* methods;

    ExternalMethodTable* externalMethods;

    MethodTableElement* addMethod(std::string name, StmtListNode* body, std::string descriptor, std::vector<MethodAccessFlag> flags);
};

/*! Тип константы в таблице констант. */
enum ConstantType
{
    Utf8_C = 1,
    Class_C = 7,
    MethodRef_C = 10,
    NameAndType_C = 12,
    Integer_C = 3,
    Double_C = 6,
    FieldRef_C = 9,
    String_C = 8
};

/*! Элемент таблицы констант. */
class ConstantTableItem
{
public:
    int id; // Номер константы.
    enum ConstantType cnst; // Тип константы.
    std::string string; // Строка для Utf-8 констант.
    int Integer; // Целое число для целочисленной константы.
    double Double; // Число с плавающий точкой.
    int firstRef; // Сслыка на первую константу.
    int secRef;  // Ссылка на вторую константу.

    /*! Конструктор.
    * \param[in] type тип константы.
    * \param[in] id номер константы в таблице констант.
    * \param[in] utf8 строка-utf8.
    * \param[in] intVal целочисленное значение для цеочисленных констант.
    * \param[in] dVal значение числас плавающей точкой для дробных констант.
    * \param[in] fRef ссылка на первую контанту - номер в таблице констант.
    * \param[in] secondRef ссылка на вторую контанту - номер в таблице констант.
    */
    ConstantTableItem(enum ConstantType type, int id, std::string utf8 = NULL, int intVal = NULL, double dVal = NULL, int fRef = NULL, int secondRef = NULL);
};

/*! Таблица констант. */
class ConstantTable
{
public:
    int maxId = 1; // Текущее максимальное значение номера констант в таблице констант.
    std::map<int, class ConstantTableItem*> constants; // Словарь - таблица констант.
    ConstantTable();

    /*! Найти константу в таблице констант или добавить ее в таблицу, если отсутствуюет.
    * \param[in] type Тип константы.
    * \param[in] utf8string строка константы UTF-8.
    * \return номер константы в таблице констант, если таковая имеется; номер добавленной константы, если таковой не было.
    */
    int findOrAddConstant(enum ConstantType type, std::string utf8string = NULL, int intVal = NULL, double dVal = NULL, int fRef = NULL, int sRef = NULL);

private:

    /*! Найти константу в таблице констант.
    * \param[in] type тип константы.
    * \param[in] fRef номер константы первой ссылки.
    * \param[in] secondRef номер константы второй ссылки.
    * \param[in] intVal Переменная для целочисленных значений.
    * \param[in] dVal Переменная для дробных значений с плавающей точкой.
    * \return номер найденной константы; -1, если константа не найдена.
    */
    int findConstant(enum ConstantType type, std::string utf8string, int fRef = NULL, int secondRef = NULL, int intVal = NULL, double dVal = NULL);

};

/*! \brief Таблица внешних методов класса. */
class ExternalMethodTable
{
public:
    std::map<std::string, class ExternalMethodTableElement*> methods = {};

    ExternalMethodTableElement* addMethod(ConstantTable* constants, std::string className, std::string methodName, std::string descriptor);
};

/*! \brief Элемент таблицы внешних методов класса. */
class ExternalMethodTableElement
{
public:
    /// Ссылка на номер константы с именем метода в таблице констант.
    int _nameRef;

    /// Ссылка на номер константы с дескриптором в таблице констант.
    int _descriptorRef;

    int _methodRef;

    /// Строковое название метода.
    std::string _name;

    /// Строковый дескриптор метода.
    std::string _descriptor;

    ExternalMethodTableElement(std::string name, int nameRef, std::string descriptor, int descriptorRef, int methodRef);
};

/*! \brief Таблица методов класса. */
class MethodTable
{
public:
    std::map<std::string, class MethodTableElement*> methods;
};

/*! \brief Элемент таблицы методов класса. */
class MethodTableElement
{
public:
    /// Ссылка на номер константы с именем метода в таблице констант.
    int methodName;

    /// Ссылка на номер константы с дескриптором в таблице констант.
    int descriptor;

    /// Строковое название метода.
    std::string strName;

    /// Строковый дескриптор метода.
    std::string strDesc;

    // Объявление метода
    class StmtListNode* _body;

    /// Ссылка на таблицу локальных переменных.
    class LocalVariableTable* varTable = NULL;

    int accessFlag;

    MethodTableElement(ConstantTable* constants, std::string name, StmtListNode* body, std::string descriptor, std::vector<MethodAccessFlag> flags);

};

class LocalVariableElement
{
public:
    std::string name; // Имя локальной переменной.
    TypeNode* _type; // Тип локальной переменной.
    int localId;

    int start_pc = 0;
    int length = 9;
    int nameIndex;
    int descriptorIndex;

    LocalVariableElement(int localId, std::string name, TypeNode* type, ConstantTable* constantTable);
};

/*! \brief Таблица локальных переменных. */
class LocalVariableTable
{
public:
    /// Контейнер элементов.
    std::map<std::string, class LocalVariableElement*> items = {};

    LocalVariableElement* addLocalVar(std::string name, TypeNode* type, ConstantTable* constantTable);

    LocalVariableElement* findLocalVar(std::string name);
};